apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  annotations:
    kubemate.mgoltzsche.github.com/nav-title: "Sample App" # kpt-set: ${title}
spec:
  ingressClassName: kubemate
  rules:
  - http:
      paths:
      - path: /sample-app/ # kpt-set: /${name}/
        pathType: Prefix
        backend:
          service:
            name: sample-app-svc # kpt-set: ${name}-svc
            port:
              number: 8080 # kpt-set: ${port}
