apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: sample-app- # kpt-set: ${name}-
commonLabels:
  app.kubernetes.io/name: sample-app # kpt-set: ${name}
resources:
- serviceaccount.yaml
- service.yaml
- deployment.yaml
- ingress.yaml
