# This is the base overlay that provides the minimal generic configuration (namespace-agnostic, ideally).
# Project-specific kustomization changes should be defined here.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../boilerplate
