apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  ports:
  - port: 8080 # kpt-set: ${port}
    targetPort: 8080 # kpt-set: ${port}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: sample-app # kpt-set: ${name}
