# Define the application name and image here.
# To apply the change to kustomization.yaml and skaffold.yaml, call:
#   make kpt-fn-render
# and commit the changes afterwards.
apiVersion: v1
kind: ConfigMap
metadata:
  name: fn-setter-config
data:
  app-name: "some-app"
  image-name: "nginxdemos/nginx-hello"
  image-tag: "0.2"
