{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "labels.standard" . | nindent 4 }}
    app: {{ .Release.Name }}
  annotations:
    kubemate.mgoltzsche.github.com/nav-title: {{ default .Release.Name .Values.nav.title | quote }}
    {{- if .Values.nav.iconURL }}
    kubemate.mgoltzsche.github.com/nav-icon: {{ .Values.nav.iconURL }}
    {{- end }}
  {{- if .Values.ingress.class }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  {{- end }}
  {{- if gt (len .Values.ingress.annotations) 0 }}
  {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}
  rules:
    - {{ if .Values.ingress.host -}}host: {{ .Values.ingress.host }}{{- end }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
  {{- if and .Values.ingress.host .Values.ingress.tlsSecret }}
  tls:
    - hosts:
      - {{- .Values.ingress.host }}
      secretName: {{- .Values.ingress.tlsSecret }}
  {{- end }}
{{- end }}
