apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}{{ if .Values.kptSetter -}}{{ " # kpt-set: ${app-name}" }}{{ end }}
  labels: {{- include "labels.standard" . | nindent 4 }}
  {{- if .Values.service.annoations }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
  selector: {{- include "labels.standard" . | nindent 4 }}
