apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "labels.standard" . | nindent 4 }}
    app: {{ .Release.Name }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}
