{{- if .Values.skaffold }}
apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: data
build:
  artifacts:
  - image: {{ .Values.image.repository }}
    docker:
      dockerfile: Dockerfile
  local:
    push: false
manifests:
  kustomize:
    paths:
    - config/default
{{- end }}
