apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: data
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: nginxdemos/nginx-hello # kpt-set: ${image}
    docker:
      dockerfile: Dockerfile
  local:
    push: false
manifests:
  kustomize:
    paths:
    - ./deploy/default
profiles:
- name: release
  build:
    platforms:
    - linux/arm64/v8
    - linux/amd64
    local:
      push: true
      useBuildkit: true
