image:
  # image.repository -- The registry and image name for the application.
  repository: "nginxdemos/nginx-hello"

  # image.tag -- Docker image tag.
  tag: "0.2"

  # image.pullPolicy -- Image pull policy.
  pullPolicy: "IfNotPresent"

# env -- Environment variables for the application.
# An object with env var names as keys.
env: {}
#  MYVAR: myvalue

resources:
  # resources.limits -- Hard resource constraints for the application.
  # When it attempts to allocate more resources it gets killed (and restarted eventually).
  limits:
    cpu: 200m
    memory: 64Mi
  # resources.requests -- Resource constraints for the application.
  # The amount of resources the process requires usually.
  # This information is used by the Pod scheduler to distribute workloads across all available nodes/machines and to avoid overloading a single node.
  # The application may still allocate more resources.
  requests:
    cpu: 100m
    memory: 32Mi

livenessProbe:
  # livenessProbe.path -- Path to the liveness probe / health check endpoint.
  path: "/healthz"
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  # readinessProbe.path -- Path to the readiness probe endpoint.
  path: "/healthz"
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1

# replicas -- Number of Pods that should be scheduled to run this app.
replicas: 1

service:
  # service.type -- Service type, e.g. `ClusterIP`, `NodePort`, `LoadBalancer`.
  type: ClusterIP
  # service.port -- Internal container port.
  port: 8080
  annotations: {}

ingress:
  # ingress.enabled -- Expose the application outside the cluster via HTTP.
  enabled: true
  # ingress.class -- The ingress class name.
  # The default exposes the app only when deployed to kubemate.
  # When you want the app to be exposed without authentication within any Kubernetes cluster, set this value to an empty string.
  class: kubemate
  annotations: {}
  # ingress.host -- The host name under which the application should be published.
  # Defaults to the kubemate node host.
  host: ""
  # ingress.paths -- The path prefixes under which the application should be exposed.
  # Defaults to `/<appname>/`.
  paths: []
  tlsSecret: ""

nav:
  # nav.title -- The navigation entry title within kubemate UI.
  # Defaults to release name.
  title: ""
  # nav.iconURL -- Optional navigation entry icon URL.
  iconURL: ""

# kptSetter -- Enables kpt setter generation.
# To use the setters afterwards, see https://catalog.kpt.dev/apply-setters/v0.2/
kptSetter: false

# skaffold -- Generates a skaffold.yaml file when enabled.
skaffold: false
