apiVersion: blueprints.kubemate.mgoltzsche.github.com/v1alpha1
kind: Webapp
metadata:
  name: sample-app
values:
  image:
    repository: nginxdemos/nginx-hello
  #service:
  #  port: 8080
  #ingress:
  #  path: /
  skaffold: true
outputPath: deploy/generated/
outputPathMapping:
- outputPath: skaffold.yaml
  selectors:
  - apiVersion: skaffold/v3alpha1
    kind: Config
