# kpt setter values that are applied to other KRM yaml files by `kpt fn render`.
# See also: https://kpt.dev/guides/variant-constructor-pattern
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # TODO: Set your project-specific configuration here!
  name: blueprint
  title: Your App Title
  image-name: nginxdemos/nginx-hello
  image-tag: "0.2"
  port: 8080
  healthcheck: /healthz
