# kpt setter values that are applied to other KRM yaml files by `kpt fn render`.
# See also: https://kpt.dev/guides/variant-constructor-pattern
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  version: "0.2"
  # TODO: Set your project-specific configuration below!
  name: blueprint
  title: Your App Title
  # ghcr.io/yourgithubuser/name
  image: nginxdemos/nginx-hello
  port: 8080
  healthcheck: /healthz
