apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: data
  annotations:
    kubemate.mgoltzsche.github.com/platforms: linux/arm64/v8,linux/amd64
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: nginxdemos/nginx-hello # kpt-set: ${image}
    docker:
      dockerfile: Dockerfile
  local:
    push: false
manifests:
  kustomize:
    paths:
    - ./deploy/default
